### ISSUE TITLE
Cog files for deploying Yi models?

### ISSUE THREAD

**Issue by ifsheldon** [01-ai/Yi#462]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

I'd like to publish my finetuned Yi models on Replicate, so I need to write Cog files, but if you have these in your Yi Playground on Replicate, maybe you can also share them as well?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Yimi81** [comment]
I only have the COG file for the vl model here
cog.yml:
```yml
# Configuration for Cog ⚙️
# Reference: https://github.com/replicate/cog/blob/main/docs/yaml.md

build:
  # set to true if your model requires a GPU
  gpu: true
  cuda: "11.8"
  python_version: "3.10"

  # a list of packages in the format <package-name>==<version>
  python_packages:
    - "torch==2.1.2"
    - "torchvision"
    - "transformers"
    - "sentencepiece"
    - "datasets"
    - "accelerate"

# predict.py defines how predictions are run on your model
predict: "predict.py:Predictor"
```

predict.py:
```python
# Prediction interface for Cog ⚙️
# https://github.com/replicate/cog/blob/main/docs/python.md

import torch
import os
from cog import BasePredictor, Input, Path
from llava.conversation import conv_templates
from llava.mm_utils import (
    KeywordsStoppingCriteria,
    expand2square,
    get_model_name_from_path,
    load_pretrained_model,
    tokenizer_image_token,
)
from llava.model.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX, key_info
from PIL import Image

MODEL_NAME = "01-ai/Yi-VL-34B"

class Predictor(BasePredictor):
    def setup(self) -> None:
        """Load the model into memory to make running multiple predictions efficient"""
        model_path = os.path.expanduser(MODEL_NAME)
        key_info["model_path"] = model_path
        get_model_name_from_path(model_path)
        self.tokenizer, self.model, self.image_processor, _ = load_pretrained_model(model_path)

    def predict(
        self,
        image: Path = Input(description="Input image."),
        query: str = Input(
            description="Input query.", default="Describe this image."
        ),
    ) -> Path:
        """Run a single prediction on the model"""
        model = self.model
        tokenizer = self.tokenizer
        image_processor = self.image_processor

        query = DEFAULT_IMAGE_TOKEN + "\n" + query
        conv = conv_templates["mm_default"].copy()
        conv.append_message(conv.roles[0], query)
        conv.append_message(conv.roles[1], None)
        prompt = conv.get_prompt()

        input_ids = (
            tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt")
            .unsqueeze(0)
            .cuda()
        )

        image = Image.open(image)
        if getattr(model.config, "image_aspect_ratio", None) == "pad":
            image = expand2square(
                image, tuple(int(x * 255) for x in image_processor.image_mean)
            )
        image_tensor = image_processor.preprocess(image, return_tensors="pt")[
            "pixel_values"
        ][0]

        stop_str = conv.sep
        keywords = [stop_str]
        stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)
        with torch.inference_mode():
            output_ids = model.generate(
                input_ids,
                images=image_tensor.unsqueeze(0).to(dtype=torch.bfloat16).cuda(),
                do_sample=True,
                temperature=0.2,
                top_p=1.0,
                num_beams=1,
                stopping_criteria=[stopping_criteria],
                max_new_tokens=1024,
                use_cache=True,
            )

        input_token_len = input_ids.shape[1]
        n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()
        if n_diff_input_output > 0:
            print(
                f"[Warning] {n_diff_input_output} output_ids are not the same as the input_ids"
            )
        outputs = self.tokenizer.batch_decode(
            output_ids[:, input_token_len:], skip_special_tokens=True
        )[0]
        outputs = outputs.strip()

        if outputs.endswith(stop_str):
            outputs = outputs[: -len(stop_str)]
        outputs = outputs.strip()

        return outputs


```
